UI ntc selector
rte-i/Antares_Simulator pull request #12
Opened 2022-03-02 12:39 UTC by Milos-RTEi

2022-03-02 12:46 UTC, Milos-RTEi commented
Apparently in Antares you cannot use upper case letters in key values of a map. 
Like: "section->add("set-11-**NTC**-to-null-for-adq-patch", setToZero11LinksForAdequacyPatch);"
I figured that out after 2 hours of debugging :(

2022-03-02 12:52 UTC, Milos-RTEi commented
If anybody has prettier/simpler/more understandable name for the UI interface than ""Adequacy patch NTC 1->2"" &""Adequacy patch NTC 1<->1"" please make a suggestion!
I don't like mine either.

2022-03-03 02:29 UTC, rtei-pw commented
> If anybody has prettier/simpler/more understandable name for the UI interface than ""Adequacy patch NTC 1->2"" &""Adequacy patch NTC 1<->1"" please make a suggestion! I don't like mine either.

"allow ntc between physical areas", 
"allow ntc only between physical areas outside adq patch"

2022-03-03 02:39 UTC, rtei-pw approved these changes, later dismissed

2022-03-03 02:39 UTC, rtei-pw commented on src/libs/antares/study/parameters.h
> +    //! Transmission capacities options for links between area type 1 and area type 2, for adequacy
maybe detail a bit the doc.
like no ntc for link between physical ares inside and outside adq patch
no ntc for link between physical areas outside adq patch

2022-03-03 10:32 UTC, Milos-RTEi commented on src/libs/antares/study/parameters.h
> +    //! Transmission capacities options for links between area type 1 and area type 2, for adequacy
Comments improved!

2022-03-04 02:42 UTC, rtei-pw approved these changes

2022-03-07 12:17 UTC, hugo-antoine-rtei requested changes
I think the only thing that's missing now is to plug this into the SetNTCForAdequacyFirstStep call in the src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp file

2022-03-07 12:54 UTC, hugo-antoine-rtei approved these changes

2022-03-08 06:37 UTC, merged