adq patch selector for each area in ui
rte-i/Antares_Simulator pull request #3
Opened 2022-01-27 10:50 UTC by rtei-pw

2022-01-27 23:25 UTC, hugo-antoine-rtei requested changes
I propose:
- Rebase once PR #4 is merged (format of area.cpp will be conflicting) - I'll wait your approval
- clang-format the files you changed

2022-01-27 23:25 UTC, hugo-antoine-rtei commented on src/libs/antares/study/area/list.cpp
> +    section->add("use-adequacy-patch", static_cast<bool>(area.bUseAdequacyPatch));
static cast not required see [here](https://github.com/AntaresSimulatorTeam/Antares_Simulator/pull/532#discussion_r793292520)

2022-01-28 00:35 UTC, rtei-pw commented
> I propose:
> 
> * Rebase once PR #4 is merged (format of area.cpp will be conflicting) - I'll wait your approval
> * clang-format the files you changed

PR #4 is merged; clang format modified

2022-01-28 00:37 UTC, hugo-antoine-rtei approved these changes
looks good !

2022-01-28 02:31 UTC, merged