[WIP] Create separate tab for adequacy patch options
rte-i/Antares_Simulator pull request #36
Opened 2022-04-07 09:51 UTC by Milos-RTEi

2022-04-08 13:28 UTC, Milos-RTEi commented
Hi! Take a look of what I have done so far, if you have a chance. 
I completed and grouped the adq. options/buttons in one window (and *.ini file and code). 
I will start the area data in the separate window first, and join them later if necessary.

2022-04-11 21:42 UTC, Milos-RTEi commented
Hi guys! i got stuck and need some help with c++ debugging.

If you pull this pr and try to build antares you will get an error: "/src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-areas.cpp:70: undefined reference to `Antares::Component::Datagrid::Renderer::AdequacyPatchAreaGrid::AdequacyPatchAreaGrid()"

I clearly created AdequacyPatchAreaGrid() class in new *.h and *.cpp files and linked them properly with #include "paths".
Spent hours on google/forums trying to figure out what is the problem. It's a very common problem and lots of proposed solutions but nothing worked. As usual I just followed the same procedure as for some other similar 'window" where this works fine, and it does not work here,
 Please take a look. When this is resolved rest of the solution should work just fine.

2022-04-12 20:48 UTC, rtei-pw requested changes

2022-04-12 20:48 UTC, rtei-pw commented on src/libs/antares/study/parameters.cpp
> +        return false;
?

2022-04-14 07:06 UTC, Milos-RTEi commented on src/libs/antares/study/parameters.cpp
> +        return false;
Corrected.

2022-05-09 09:57 UTC, merged